options:
  emptyMessage: No achievements in this game
  id: game-achievements
  title: Game Achievements
columns:
  player:
    type: link
    labelKey: getPlayer.getName
    label: Player
    url: 'player/view'
    params:
      id: getPlayer.getId
  achievement:
    type: link
    labelKey: getAchievement.getName
    label: Achievement
    url: 'achievement/view'
    params:
      id: getAchievement.getId
  description:
    type: text
    index: getAchievement.getDescription
    label: Description
  color:
    type: text
    index: getAchievement.getAchievementColor.getName
    label: Color
