options:
  emptyMessage: There are no wonder sets.
  id: wonder-set
  title: Wonder sets
columns:
  id:
    type: integer
    index: getId
    label: Id
  name:
    type: text
    index: getName
    label: Name
    defaultSort: true
  active:
    type: yesno
    index: getActive
    label: Active
  edit:
    type: link
    index: getId
    label: Edit
    url: 'entity/edit'
    urlParams:
      entity: wonder-set
    sortable: false
    params:
      id: getId
buttons:
  new:
    label: Add New Wonders Set
    url: 'entity/new'
    params:
      entity: wonder-set